# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Refer to https://mmistakes.github.io/minimal-mistakes/docs/configuration/

title: SUAS Blog
email: usydastronomy@gmail.com
name: Sydney University Astronomy Society
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the Sydney University Astronomy Society (SUAS) blog!
  We are a group of students from The University of Sydney,
  passionate about astronomy and all things space.
domain: "blog.usydastro.org.au"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.usydastro.org.au" # the base hostname & protocol for your site, e.g. http://example.com

minimal_mistakes_skin: "dark"
search: true
title_separator: "|"
#subtitle: "Version 2.0"
permalink: /:categories/:title/
paginate_path: /page:num/
timezone: Australia/Sydney # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
locale: "en"

teaser: /assets/images/telescope_red_light.jpg # Default teaser image
logo: /assets/images/Emblem_(Mono_White).svg
og_image: /assets/images/Logo.png

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      comments: false
      share: true
      related: true
      author_profile: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

facebook:
  username: "usydastronomy"

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/usydastronomy"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/usydastro"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/usydastronomy
    - label: "E-Mail"
      icon: "fas fa-fw fa-envelope"
      url: mailto:usydastronomy@gmail.com

# Build settings
#theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include: ["_pages"]
exclude:
  - CNAME
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
